### ISSUE TITLE
Issues with current code

### ISSUE THREAD

**Issue by offlinehacker** [ripple/ripple-data-api#30]
I have a few problems with running current (master) version of ripple-data-api. As far as i can see new api is trying to connect to hbase and retrive data from there. There error i get is:

```
{
    "error": "thrift connection timeout"
}
```

This error occurs even if i'm running hbase with thrift started. As far as i can see importer is not importing data into hbase, but still imports to couchdb as before. So my question is how to use current version of ripple data api? Are you now using importer from https://github.com/ripple/rippled-historical-database.

Another question i have is which commit is current "stable" version of ripple-data-api, which version do you use at ripple labs? With older "versions" api works for us, but import process seem to stop(stop not crash) at some point and new ledgers are not imported anymore. 

Thanks!

**Comment by shekenahglory** [comment]
The 'legacy' branch is the last commit before switching the data source to hbase, so if you only want to use couchDB, use that.  Our current version is master, however the import is now done via storm using https://github.com/ripple/rippled-historical-database.  You should use the importer from there, even for couchDB.  you don't have to use storm though - just `node import/live.js --type hbase` or `node import/live.js --type couchdb`

**Comment by shekenahglory** [comment]
what version of hbase are you using? hbase comes with 2 version of thrift, we are using thrift1 and it needs to be set to framed transport for node.js clients.

**Comment by offlinehacker** [comment]
Thanks! So changing thrift to framed transport did the trick. I'm testing new import right now. Are there any extra benefits with using storm for import, besides being HA?

**Comment by offlinehacker** [comment]
Should i do import in both databases, because code here, seems to use hbase and couchdb?

**Comment by shekenahglory** [comment]
Ah I forgot, storm is doing realtime aggregation of the data, while the other import is not, so if you need tick data for exchanges, you might want to use that.  The main reason for using storm was for scalability, if we need multiple machines to keep up with the incoming transactions.  For now, a single machine running storm handles it just fine.  You could also write a script that uses the exchange aggregation module separately if you didn't want to bother with storm.

**Comment by shekenahglory** [comment]
I'd just use hbase unless you have some reason to keep going with couchdb.

**Comment by offlinehacker** [comment]
Ok, makes sense. But as i can see some api calls still use old api that uses couchdb and we are using an api call from there, so in that case i should still be importing to couchdb and have old design documents loaded in couchdb, am i right?

**Comment by shekenahglory** [comment]
Which API call is it? most of the functionality is being brought over to the history API, which pulls from postgres and hbase right now but eventually everything will be from hbase.

**Comment by offlinehacker** [comment]
We currently use total_value_sent, offers_exercised and exchange_rates. Currently i deployed legacy version, as this is also the one you seem to use on http://api.ripplecharts.com/api, but we would like to try to migrate to new historical api.

**Comment by shekenahglory** [comment]
total_value_sent is going to be deprecated, and replaced with payment_volume from hbase, but it depends on aggregated data so you'd have to be running storm and/or performing batch aggregations.  http://api.ripplecharts.com/api is actually deployed on the master branch now, with some data coming from hbase and some from couchdb.

**Comment by offlinehacker** [comment]
I was thinking that too, but if i do POST on `https://api.ripplecharts.com/api/payments` i get:

```
Sorry, that API route doesn't seem to exist. Available paths are: offers, offersexercised, topmarkets, totaltradevolume, markettraders, accountscreated, issuercapitalization, currencybalances, totalnetworkvalue, exchangerates, valuesent, totalvaluesent, accounttransactions, accounttransactionstats, accountoffersexercised, accounttrust, transactionstats, ledgersclosed, historicalmetrics
```

Thanks for explanation, we will deploy new historical ripple api and test it, hopefully i find some time for contributions.

**Comment by shekenahglory** [comment]
payments endpoint is still on the develop branch

**Comment by offlinehacker** [comment]
Are you using new importer to import into couchdb. Currently we are having an issue with legacy importer, that it only imports for some time and then we are getting errors like:

```
Apr 29 23:28:11 hub1 importer[20761]: error: error getting ledger: {"result":{"error":"lgrNotFound","error_code":20,"error_message":"ledgerNotFound","request":{"command":"ledger","expand":true,"ledger_index":13102678,"transactions":true},"status":"error"}}
Apr 29 23:28:11 hub1 importer[20761]: error: problem getting ledger batch: error=ledger 13102678 not available from any of the rippleds, retry=true
```

Any idea what could be the problem?

**Comment by shekenahglory** [comment]
are you connecting to s1.ripple.com?

**Comment by offlinehacker** [comment]
We are connecting to our own rippled instance, which seems to run without any issues(no skipped ledgers or similar problems), at least trading app we are testing for some time runs fine.

**Comment by shekenahglory** [comment]
Try s1, I know I've seen that error before, but I'm not sure what the exact circumstances were.  I've never run it connected to a local rippled.

**Comment by offlinehacker** [comment]
Ok we are testing it now, looks good so far. If you have any idea what could be the problem with our rippled(if this is rippled related problem), please let us know.

**Comment by offlinehacker** [comment]
Ok, it does still seem not to work, i don't have problem described in previous posts, but i still get:

```
info: Incomplete ledger history over the last 24 hours
```

Data is still not updated.

**Comment by shekenahglory** [comment]
the error you are seeing is because its trying to check couchDB to determine if its up to date, you should not get this error on the develop branch, or on the master you can comment out this line:

'https://github.com/ripple/ripple-data-api/blob/master/api/app.js#L299'

Which data are you saying is not updated?

**Comment by offlinehacker** [comment]
Currently i'm testing with offersexercised and it seems like by observations, that after some time imported data stays behind. For example if i do POST on https://ripple.gatehub.net/api/offersexercised it does not return up to date results comparing to https://api.ripplecharts.com/api/offersexercised

This is our database config:

```
{
   "production":{
      "database":"rippled",
      "host":"localhost",
      "password":[
         "**********"
      ],
      "port":5984,
      "protocol":"http",
      "username":[
         "rippled"
      ]
   }
}
```

and config for deployment envs:

```
{  
   "production":{  
      "batchSize":100,
      "maxSockets":150,
      "port":"5993",
      "redis":{  
         "enable":true,
         "host":"localhost",
         "options":{  
            "auth_pass":null
         },
         "port":5984
      },
      "rippleds":[  
         "http://s1.ripple.com:51234/"
      ],
      "startIndex":12706501
   }
}
```

**Comment by offlinehacker** [comment]
After i restarted importer, i also get bunch of these errors:

```
error: Error calculating transaction hash: 13242964 Error: Value is not a number (TransactionResult)
```

**Comment by offlinehacker** [comment]
Which version of couchdb are you running?

**Comment by shekenahglory** [comment]
looks like we are running version 1.0.2 - are you running the import/live.js script?  CouchDB has a quirk where incoming data only gets indexed when it is queried, so that script has a component to ping the views to trigger indexing: https://github.com/ripple/rippled-historical-database/blob/develop/import/live.js#L77

**Comment by offlinehacker** [comment]
After using importer from ripple-historical-database, it seems it works
fine :)

**Comment by offlinehacker** [comment]
I will close this issue request now, as usage of new importer(from ripple-historical-database) solves problems with missing data. I still have no idea what's causing problems with legacy importer, but i will not spend anymore time dealing with this problem, as new importer works and has better design and should be easier to debug.

Our final working solution is to use couchdb design documents and api from here(legacy branch) and couchdb importer from ripple-historical-database. In following days i will deploy storm on mesos and also start importing into hbase, then i will try and switch from legacy to master branch.
